version: '3.8'

services:
  db:
    image: postgres:16
    container_name: mi-api-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  app:
    build: .
    container_name: mi-api-app
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT:-3001}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
